let correctnessCheck = {
    "question01": [
        { "name": "01", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "16", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "17", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "18", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "19", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "20", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "21", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "22", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "23", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "24", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "25", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "26", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "27", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "28", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "29", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false }
    ],
    "question02": [
        { "name": "01", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "16", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "17", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "18", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "19", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "20", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "21", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "22", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "23", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "24", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "25", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false }
    ],
    "question03": [
        { "name": "01", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "16", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "17", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "18", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false }
    ],
    "question04": [
        { "name": "01", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "16", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false }
    ],
    "question05": [
        { "name": "01", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "16", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "17", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "18", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false }
    ],
    "question06": [
        { "name": "01", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false }
    ],
    "question07": [
        { "name": "01", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "16", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "17", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "18", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false }
    ],
    "question08": [
        { "name": "01", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "02", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "03", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "04", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "05", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "06", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "07", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "08", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "09", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": true },
        { "name": "10", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "11", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "12", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "13", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "14", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "15", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "16", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "17", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "18", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "19", "isCorrect": true, "isClicked": false, "isLastlyDisplayed": false },
        { "name": "20", "isCorrect": false, "isClicked": false, "isLastlyDisplayed": false }
    ]
}

let numberOfQuestions = [
    { "name": "question01", "id": "01", "title": "自動車", "isAnswered": false },
    { "name": "question02", "id": "02", "title": "横断歩道", "isAnswered": false },
    { "name": "question03", "id": "03", "title": "UFO", "isAnswered": false },
    { "name": "question04", "id": "04", "title": "チワワ", "isAnswered": false },
    { "name": "question05", "id": "05", "title": "プードル", "isAnswered": false },
    { "name": "question06", "id": "06", "title": "ハムスター", "isAnswered": false },
    { "name": "question07", "id": "07", "title": "モダンアート", "isAnswered": false },
    { "name": "question08", "id": "08", "title": "カレイ", "isAnswered": false }
]